version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    environment:
      NAISPLATER_VERSION: 0.0.0
      KUBECTL_IMAGE_TAG: v1.10.0
      NAISCAPER_VERSION: 8.0.0
      CLUSTER_NAME: nais-dev-aks-name
      RESOURCE_GROUP: nais-dev-aks-rg
    steps:
      - checkout
      - setup_remote_docker
      # generate valid kubeconfig via gcloud cli
      - run: 
          name: Generate valid kubeconfig via azure-cli
          command: |
            docker run --name azure-cli microsoft/azure-cli bash -c "az login --service-principal --user ${SP_NAME} --password ${SP_PASS} --tenant ${AZURE_TENANT}; az aks get-credentials --name nais-dev-aks-name --resource-group nais-dev-aks-rg;az acs kubernetes install-cli;"
            docker cp azure-cli:/root/.kube/config kubeconfig
      - run:
          name: List pods
          command: |
            docker create -v /root/.kube/ --name files2 alpine:3.4 /bin/true
            docker cp `pwd`/kubeconfig files2:/root/.kube/config
            docker run --name kubectl --volumes-from files2 lachlanevenson/k8s-kubectl:${KUBECTL_IMAGE_TAG} get pods
