version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    environment:
      NAISPLATER_VERSION: 0.0.0
      KUBECTL_IMAGE_TAG: v1.10.0
      NAISCAPER_VERSION: 8.0.0
      CLUSTER_NAME: nais-dev-aks-name
      RESOURCE_GROUP: nais-dev-aks-rg
    steps:
      - checkout
      - setup_remote_docker
      # generate valid kubeconfig via gcloud cli
      - run: 
          name: Generate valid kubeconfig via gcloud cli
          command: |
            docker create -v /files --name files1 alpine:3.4 /bin/true
            openssl aes-256-cbc -d -md md5 -in `pwd`/${CLUSTER_NAME}-credentials.pem.enc -out `pwd`/sp-credentials.pem -k ${ENC_KEY}
            docker cp `pwd`/sp-credentials.pem files1:/files
            docker run --name gcloud --volumes-from files1 navikt/gcloud:1 bash -c "az login --password sp-credentials.pem; kubectl get pods"
            docker cp gcloud:/root/.kube/config kubeconfig

